name: Main Workflow

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '*/2 * * * *'
  #   - cron: '*/3 * * * *'

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          if [ "${{ github.event.schedule }}" = "*/2 * * * *" ]; then
            echo "matrix={\"environment\":[\"env1\",\"env2\"]}" >> $GITHUB_OUTPUT
          else
            echo "matrix={\"environment\":[\"env1\"]}" >> $GITHUB_OUTPUT
          fi

  build:
    needs: matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.matrix.outputs.matrix) }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run a one-line script
      run: |
        echo "Hello, GitHub Actions! Running in environment: ${{ matrix.environment }}" 