name: Main Workflow

on:
  workflow_dispatch:
    inputs:
      dev:
        description: 'Run in development mode'
        required: true
        type: boolean
        default: false
  schedule:
    - cron: '25,30 * * * *'

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] || [ "${{ github.event.schedule }}" = "25 * * * *" ]; then
            echo "matrix={\"environment\":[\"env1\"]}" >> $GITHUB_OUTPUT
          else
            echo "matrix={\"environment\":[\"env1\",\"env2\"]}" >> $GITHUB_OUTPUT
          fi

  build:
    needs: matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.matrix.outputs.matrix) }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run a one-line script
      run: |
        echo "Hello, GitHub Actions! Dev mode: ${{ github.event.inputs.dev }} in environment: ${{ matrix.environment }}" 